version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: 5432
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - menetlus
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - menetlus
    depends_on:
      - postgres
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.2-management
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    networks:
      - menetlus
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - ${BACKEND_PORT}:8080
    networks:
      - menetlus
    depends_on:
      - postgres
  mail-service:
    container_name: mail-service
    build:
      context: ./mail-service
    restart: always
    networks:
      - menetlus
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:4200
    networks:
      - menetlus
    depends_on:
      - backend

networks:
  menetlus:
    driver: bridge

volumes:
  pgdata: