application:
  rabbitMq:
    durable: true
    queueName: ""
    topicExchangeName: ""
    headerExchangeName: ""
    directExchangeName: ""
    fanoutExchangeName: ""
    headerArgument: ""
    routingKey: ""
    directRoutingKey: "direct"