application:
  rabbitMq:
    durable: true
    queueName: menetlus.mail
    exchangeName: menetlus-mail-exchange
    routingKey: menetlus.mail.request

spring:
  application:
    name: Menetlus
  datasource:
    url: jdbc:postgresql://postgres/menetlus
    driver-class-name: org.postgresql.Driver
    username: menetlus
    password: parool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq