application:
  rabbitMq:
    durable: true
    queueName: "menetlus-rabbitmq"
    topicExchangeName: "menetlus-topic-exchange"
    headerExchangeName: "menetlus-headers-exchange"
    directExchangeName: "menetlus-direct-exchange"
    fanoutExchangeName: "menetlus-fanout-exchange"
    headerArgument: "testId"
    routingKey: "menetlus.#"
    headerRoutingKey: "header.#"
    directRoutingKey: "direct"
    fanoutRoutingKey: " "

spring:
  application:
    name: Menetlus
  datasource:
    url: jdbc:postgresql://postgres/menetlus
    driver-class-name: org.postgresql.Driver
    username: menetlus
    password: parool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq